language: generic
sudo: required
services:
  - docker
deploy:
  provider: gae
  project: kubernetes-course-279208
  keyfile: google_app.json
  verbosity: debug
  on:
    branch: master

before_install:
  - openssl aes-256-cbc -K $encrypted_aeba2e348097_key -iv $encrypted_aeba2e348097_iv
  -in google_app.json.enc -out google_app.json -d
  - docker build -t astrego/test-cicd -f Dockerfile .
